language: cpp

compiler:
 - gcc
 - clang

before_script:
 - echo "yes" | sudo add-apt-repository ppa:kalakris/cmake
 - sudo apt-get update -qq
 - sudo apt-get install cmake

script:
 - mkdir build && cd build && cmake .. && make 

os:
 - linux
 - osx
 
osx_image: xcode61